name: Launcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Publish
      run: dotnet publish ./launcher/launcher.csproj --runtime win-x64 -p:PublishSingleFile=true --self-contained false --framework net8.0-windows7.0
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
         name: Launcher_Artifact
         path: ./launcher/bin/Release/net8.0-windows7.0/win-x64/publish/launcher.exe
